// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epgrekvkbxyakguphooy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwZ3Jla3ZrYnh5YWtndXBob295Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTU5NjcsImV4cCI6MjA3MDQzMTk2N30.cTiaqNwL2azLOXf9G-M30oOoIwo19O0HV08sj_snORA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});